version: '3.8'

networks:
  todoapp-net:

services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PYTHONUNBUFFERED: 1
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      DB_PORT: 3306
    env_file:
      - .env
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]

  mysql:
    image: mysql:8.0
    container_name: my-sql
    ports:
      - "3307:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - todoapp-net

volumes:
  todoapp-db-data: